//routes/user.js
import express from "express";
import { Folder, Page } from "../Schema/FolderSchema.js";
import protectRoute from "../middleWare/authMiddleWare.js";
import mongoose from "mongoose";

const router = express.Router();

router.post("/folder-create", protectRoute, async (req, res) => {
  const { title, description, color, favourite, tags, icons } = req.body;
  const createdBy = req.user._id;

  if (!title) {
    return res.status(400).json({ message: "Title must be present" });
  }

  try {
    const newFolder = await Folder.create({
      createdBy: createdBy,
      title: title,
      description: description,
      color: color,
      favourite: favourite,
      tags: tags || [],
      icons: icons,
      pages: [],
    });

    res.status(201).json(newFolder);
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: "Server error during folder creation",
      error: error.message,
    });
  }
});

router.get("/getAll", protectRoute, async (req, res) => {
  try {
    const data = await Folder.find({ createdBy: req.user._id })
      .populate("pages")
      .lean();
    return res.status(200).json({ message: "Retrieved", data: data });
  } catch (error) {}
});

router.put("/page-create/:noteBookID", protectRoute, async (req, res) => {
  const { title, pageContent, tags } = req.body;
  const { noteBookID } = req.params;

  if (!title) return res.status(400).json({ message: "Title is required" });

  try {
    const folder = await Folder.findOne({
      _id: noteBookID,
      createdBy: req.user._id,
    });

    if (!folder) {
      return res
        .status(404)
        .json({ message: "Notebook not found or you do not have access." });
    }

    // FIX 1: Use the Mongoose Page Model to create and save the document to the DB
    const newPage = await Page.create({
      page: title, // Your schema uses 'page' for the title/main content
      pageContent: pageContent, // Your schema has a separate pageContent field
      tags: tags || [],
    });

    // FIX 2: Push the valid MongoDB ObjectId (the actual ID generated by the DB)
    folder.pages.push(newPage._id);
    await folder.save(); // Save the updated folder document

    res.status(201).json({
      message: "Page created and added to notebook successfully",
      page: newPage, // This is now a full Mongoose document
      folder: folder.title,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: "Server error during page creation",
      error: error.message,
    });
  }
});

// PATCH /user/folder-update/:folderID
router.patch("/folder-update/:folderID", protectRoute, async (req, res) => {
  const { folderID } = req.params;

  try {
    // 1. Validate ID format immediately
    if (!mongoose.Types.ObjectId.isValid(folderID)) {
      return res.status(400).json({ message: "Invalid Folder ID format" });
    }

    // 2. Build dynamic update object (Only include what is sent)
    const updates = {};
    const fields = [
      "title",
      "description",
      "color",
      "favorite",
      "tags",
      "icons",
    ];

    fields.forEach((field) => {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
      }
    });

    // 3. Perform the update
    const updatedFolder = await Folder.findOneAndUpdate(
      { _id: folderID, createdBy: req.user._id },
      { $set: updates },
      { new: true, runValidators: true }, // Validators only run on the fields being updated
    );

    if (!updatedFolder) {
      return res.status(404).json({
        message: "Folder not found or you do not have permission.",
      });
    }

    res.status(200).json({
      message: "Folder updated successfully",
      data: updatedFolder,
    });
  } catch (error) {
    console.error("PATCH Error:", error);
    res.status(500).json({
      message: "Server error during folder update",
      error: error.message,
    });
  }
});

// Corrected Route
router.delete("/folder-delete/:folderId", protectRoute, async (req, res) => {
  // Use the exact name from the URL parameter (:folderId)
  const { folderId } = req.params;

  try {
    const folder = await Folder.findById(folderId);

    if (!folder) {
      return res.status(404).json({ message: "No such folder exists" });
    }

    // Optional: Check if the user owns this folder before deleting
    // if (folder.user.toString() !== req.user._id.toString()) {
    //   return res.status(403).json({ message: "Not authorized" });
    // }

    await folder.deleteOne();

    // Send a 200 (Success) or 204 (No Content) status
    res.status(200).json({ message: "Folder deleted successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Server error during deletion" });
    console.log(error);
  }
});

// Corrected Route
router.delete("/page-delete/:pageId", protectRoute, async (req, res) => {
  // Use the exact name from the URL parameter (:folderId)
  const { pageId } = req.params;

  try {
    const page = await Page.findById(pageId);

    if (!page) {
      return res.status(404).json({ message: "No such page exists" });
    }

    // Optional: Check if the user owns this folder before deleting
    // if (folder.user.toString() !== req.user._id.toString()) {
    //   return res.status(403).json({ message: "Not authorized" });
    // }

    await page.deleteOne();

    // Send a 200 (Success) or 204 (No Content) status
    res.status(200).json({ message: "Page deleted successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Server error during deletion" });
  }
});

// PATCH /user/page-update/:pageID
router.patch("/page-update/:pageID", protectRoute, async (req, res) => {
  const { pageID } = req.params;
  // Extract only the fields allowed to be updated
  const updates = {
    page: req.body.title,
    pageContent: req.body.pageContent,
    tags: req.body.tags,
  };

  try {
    // We need to check both the page's existence AND if the user owns the parent folder.
    // A common pattern is to just update the page directly and rely on security rules,
    // but since we linked folders to users, we will do a two-step check for security.

    // Step 1: Find the page and update it
    const updatedPage = await Page.findByIdAndUpdate(
      pageID,
      { $set: updates },
      { new: true, runValidators: true },
    );

    if (!updatedPage) {
      return res.status(404).json({ message: "Page not found." });
    }

    // Step 2: Ensure the user is associated with a folder that contains this page
    const ownsPage = await Folder.exists({
      createdBy: req.user._id,
      pages: pageID,
    });

    if (!ownsPage) {
      // In a real application, you might reverse the update here if this check fails
      return res
        .status(403)
        .json({ message: "You do not have permission to update this page." });
    }

    res
      .status(200)
      .json({ message: "Page updated successfully", data: updatedPage });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: "Server error during page update",
      error: error.message,
    });
  }
});

export default router;
